config/routes.rb
Rails.application.routes.draw do
  
  # get 'payments/edit'
  # get 'payments/index'
  # get 'payments/show'
  # get 'payments/delete'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments

  #get 'reports/edit'
  #get 'reports/index'
  #get 'reports/new'
  #get 'reports/show'
  #get 'exams/edit'
  # get 'exams/index'
  # get 'exams/new'
  # get 'exams/show'
  #get 'teachers/edit'
  #get 'teachers/index'
  #get 'teachers/new'
  #get 'teachers/show'
  #get 'students/edit'
  #get 'students/index'
  #get 'students/new'
  #get 'students/show'
  #get 'books/edit'
 # get 'books/index'
  #get 'books/new'
  #get 'books/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new #untuk menampilkan form data baru
    @teacher = Teacher.new
    # @teacher = Teacher.new(title: ' ')
    # @teacher = Teacher.new(page: nil)
    
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa isi params
    #title = params[:teacher][:title] ->caea mengecek balikan params
    teacher = Teacher.new(resource_params)
    teacher.save
    flash[:notice] = 'Teacher has been created'
    #puts teacher.errors.messages
    redirect_to teachers_path
  end

  def edit # menampilkan data yang sudah disimpian di edit
    @teacher = Teacher.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @teacher = Teacher.find(params[:id])
    @teacher.update(resource_params)
    flash[:notice] = 'Teacher has been updated'
    redirect_to teacher_path(@teacher)
  end

  def destroy #untuk menghapus data
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:notice] = 'Teacher has been deleted'
    redirect_to teachers_path
  end

  def index #menampilkan seluruh data yang ada di database
    @teachers = Teacher.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @teacher = Teacher.find(id) #-> id ini ngambil variabel diatas
    #render plain: id
    #render plain: @teacher.title
  end

  private

  def resource_params
    params.require(:teacher).permit(:nik, :name, :age, :kelas, :mapel)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<br>

<div class="container">
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
<%= link_to 'Cancel', teachers_path %>

<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> <br>
    <%= f.text_field :nik %> <br>

    <%= f.label :name %> <br>
    <%= f.text_field :name %> <br>

    <%= f.label :age %> <br>
    <%= f.text_field :age %> <br>

    <%= f.label :kelas %> <br>
    <%= f.text_field :kelas %> <br>

    <%= f.label :mapel %> <br>
    <%= f.text_field :mapel %> <br> <br>

    <%= f.submit "Update Teacher", class:"btn btn-success" %>
<% end %>


</div>

app/views/teachers/index.html.erb
<% if flash[:notice].present? %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th scope="col">NIK</th>
            <th scope="col">Name</th>
            <th scope="col">Age</th>
            <th scope="col">Kelas</th>
            <th scope="col">Mapel</th>
            <th scope="col">Aksi</th>
        </tr>
    </thead>
        <% @teachers.each do |teacher| %>
    <tbody>
        <tr>
            <td><%= teacher.nik %></td>
            <td><%= teacher.name %></td>
            <td><%= teacher.age %></td>
            <td><%= teacher.kelas %></td>
            <td><%= teacher.mapel %></td>
            <td><%= link_to 'Detail', teacher_path(teacher), class:"btn btn-info" %>  <%= link_to 'Edit', edit_teacher_path(teacher), class:"btn btn-warning" %>  <%= link_to 'Delete', teacher_path(teacher), class:"btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %> </td>
        </tr>
    </tbody>
    <% end %>
</table> 

<div class="-25 p-3">
    &nbsp; <%= link_to 'New Teacher', new_teacher_path, class:"btn btn-success" %>
</div>

app/views/teachers/new.html.erb
<br>
<div class="container">
    
<%= form_for(@teacher) do |f| %>
    <%= f.label :nik %> <br>
    <%= f.text_field :nik %> <br>

    <%= f.label :name %> <br>
    <%= f.text_field :name %> <br>

    <%= f.label :age %> <br>
    <%= f.text_field :age %> <br>

    <%= f.label :kelas %> <br>
    <%= f.text_field :kelas %> <br>

    <%= f.label :mapel %> <br>
    <%= f.text_field :mapel %> <br> <br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>

app/views/teachers/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> 
<br>
<br>
<div class="container">
    NIK : <%= @teacher.nik %></br>
    Name : <%= @teacher.name %></br>
    Age : <%= @teacher.age %></br>
    Kelas : <%= @teacher.kelas %></br>
    Mapel : <%= @teacher.mapel %></br>
<br>
<%= link_to 'Back to Home', teachers_path %>
</div>