config/routes.rb
Rails.application.routes.draw do
  
  # get 'payments/edit'
  # get 'payments/index'
  # get 'payments/show'
  # get 'payments/delete'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments

  #get 'reports/edit'
  #get 'reports/index'
  #get 'reports/new'
  #get 'reports/show'
  #get 'exams/edit'
  # get 'exams/index'
  # get 'exams/new'
  # get 'exams/show'
  #get 'teachers/edit'
  #get 'teachers/index'
  #get 'teachers/new'
  #get 'teachers/show'
  #get 'students/edit'
  #get 'students/index'
  #get 'students/new'
  #get 'students/show'
  #get 'books/edit'
 # get 'books/index'
  #get 'books/new'
  #get 'books/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @payment = Payment.new
    # @payment = Payment.new(title: ' ')
    # @payment = Payment.new(page: nil)
    
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa isi params
    #title = params[:payment][:title] ->caea mengecek balikan params
    payment = Payment.new(resource_params)
    payment.save
    flash[:notice] = 'Payment has been created'
    #puts payment.errors.messages
    redirect_to payments_path
  end

  def edit # menampilkan data yang sudah disimpian di edit
    @payment = Payment.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @payment = Payment.find(params[:id])
    @payment.update(resource_params)
    flash[:notice] = 'Payment has been updated'
    redirect_to payment_path(@payment)
  end

  def destroy #untuk menghapus data
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = 'Payment has been deleted'
    redirect_to payments_path
  end

  def index #menampilkan seluruh data yang ada di database
    @payments = Payment.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @payment = Payment.find(id) #-> id ini ngambil variabel diatas
    #render plain: id
    #render plain: @payment.title
  end

  private

  def resource_params
    params.require(:payment).permit(:id_transaksi, :status, :upload)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<br>

<div class="container">
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
<%= link_to 'Cancel', payments_path %>

<%= form_for(@payment) do |f| %>
    <%= f.label :id_transaksi %> <br>
    <%= f.text_field :id_transaksi %> <br>

    <%= f.label :status %> <br>
    <%= f.text_field :status %> <br>

    <%= f.label :upload %> <br>
    <%= f.text_field :upload %> <br> <br>

    <%= f.submit "Update Payment", class:"btn btn-success" %>
<% end %>
</div>

app/views/payments/index.html.erb
<% if flash[:notice].present? %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

<table class="table table-bordered" >
    <thead class="thead-dark">
    <tr>
        <th scope="col">ID Transaksi</th>
        <th scope="col">Status</th>
        <th scope="col">Upload</th>
        <th scope="col">Aksi</th>
    </tr>
    </thead>
        <% @payments.each do |payment| %>
    <tbody>
        <tr>
            <td><%= payment.id_transaksi %></td>
            <td><%= payment.status %></td>
            <td><%= payment.upload %></td>
            <td><%= link_to 'Detail', payment_path(payment), class:"btn btn-info" %>  <%= link_to 'Edit', edit_payment_path(payment), class:"btn btn-warning" %>  <%= link_to 'Delete', payment_path(payment), class:"btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %> </td>
        </tr>
    </tbody>
    <% end %>
</table> 

<div class="-25 p-3">
    <%= link_to 'New payment', new_payment_path, class:"btn btn-success"%>
</div>

app/views/payments/new.html.erb
<br>
<div class="container">
    
<%= form_for(@payment) do |f| %>
    <%= f.label :id_transaksi %> <br>
    <%= f.text_field :id_transaksi %> <br>

    <%= f.label :status %> <br>
    <%= f.text_field :status %> <br>

    <%= f.label :upload %> <br>
    <%= f.text_field :upload %> <br><br>

    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>

</div>

app/views/payments/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> </br>
<br>
<br>
<div class="container">
ID Transaksi : <%= @payment.id_transaksi %></br>
Status : <%= @payment.status %></br>
Upload : <%= @payment.upload %></br>

<br>
<%= link_to 'Back to Home', payments_path %>
</div>