config/routes.rb
Rails.application.routes.draw do
  
  # get 'payments/edit'
  # get 'payments/index'
  # get 'payments/show'
  # get 'payments/delete'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments

  #get 'reports/edit'
  #get 'reports/index'
  #get 'reports/new'
  #get 'reports/show'
  #get 'exams/edit'
  # get 'exams/index'
  # get 'exams/new'
  # get 'exams/show'
  #get 'teachers/edit'
  #get 'teachers/index'
  #get 'teachers/new'
  #get 'teachers/show'
  #get 'students/edit'
  #get 'students/index'
  #get 'students/new'
  #get 'students/show'
  #get 'books/edit'
 # get 'books/index'
  #get 'books/new'
  #get 'books/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new #untuk menampilkan form data baru
    @exam = Exam.new
    # @exam = Exam.new(title: ' ')
    # @exam = Exam.new(page: nil)
    
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa isi params
    #title = params[:exam][:title] ->caea mengecek balikan params
    exam = Exam.new(resource_params)
    exam.save
    flash[:notice] = 'Exam has been created'
    #puts exam.errors.messages
    redirect_to exams_path
  end

  def edit # menampilkan data yang sudah disimpian di edit
    @exam = Exam.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @exam = Exam.find(params[:id])
    @exam.update(resource_params)
    flash[:notice] = 'Exam has been updated'
    redirect_to exam_path(@exam)
  end

  def destroy #untuk menghapus data
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:notice] = 'Exam has been deleted'
    redirect_to exams_path
  end

  def index #menampilkan seluruh data yang ada di database
    @exams = Exam.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @exam = Exam.find(id) #-> id ini ngambil variabel diatas
    #render plain: id
    #render plain: @exam.title
  end

  private

  def resource_params
    params.require(:exam).permit(:title, :mapel, :duration, :nilai, :keaktifan, :level, :student_id)
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/edit.html.erb
<br>
<div class="container">
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
<%= link_to 'Cancel', exams_path %>

<%= form_for(@exam) do |f| %>
    <%= f.label :title %> <br>
    <%= f.text_field :title %> <br>

    <%= f.label :mapel %> <br>
    <%= f.text_field :mapel %> <br>

    <%= f.label :duration %> <br>
    <%= f.text_field :duration %> <br>

    <%= f.label :nilai %> <br>
    <%= f.text_field :nilai %> <br>

    <%= f.label :keaktifan %> <br>
    <%= f.text_field :keaktifan %> <br>

    <%= f.label :level %> <br>
    <%= f.text_field :level %> <br>

    <%= f.label :student_id %> <br>
    <%= f.text_field :student_id %> <br>

    <br>
    <%= f.submit "Update Exam", class:"btn btn-success" %>
<% end %>
</div>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

<table class="table table-bordered" >
    <thead class="thead-dark">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Mapel</th>
            <th scope="col">Duration</th>
            <th scope="col">Nilai</th>
            <th scope="col">Keaktifan</th>
            <th scope="col">Level</th>
            <th scope="col">Student ID</th>
            <th scope="col">Aksi</th>
        </tr>
    </thead>
    <% @exams.each do |exam| %>
    <tbody>
        <tr>
            <td><%= exam.title %></td>
            <td><%= exam.mapel %></td>
            <td><%= exam.duration %></td>
            <td><%= exam.nilai %></td>
            <td><%= exam.keaktifan %></td>
            <td><%= exam.level %></td>
            <td><%= exam.student_id %></td>
            <td><%= link_to 'Detail', exam_path(exam), class:"btn btn-info" %>  <%= link_to 'Edit', edit_exam_path(exam), class:"btn btn-warning" %> <%= link_to 'Delete', exam_path(exam), class:"btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %> </td>
        </tr>
    </tbody>
    <% end %>
</table> 

<div class="-25 p-3">
    &nbsp; <%= link_to 'New Exam', new_exam_path, class:"btn btn-success"%>
</div>

app/views/exams/new.html.erb
<br>
<div class="container">

    <%= form_for(@exam) do |f| %>
        <%= f.label :title %> <br>
        <%= f.text_field :title %> <br>

        <%= f.label :mapel %> <br>
        <%= f.text_field :mapel %> <br>

        <%= f.label :duration %> <br>
        <%= f.text_field :duration %> <br>

        <%= f.label :nilai %> <br>
        <%= f.text_field :nilai %> <br>

        <%= f.label :keaktifan %> <br>
        <%= f.text_field :keaktifan %> <br>

        <%= f.label :level %> <br>
        <%= f.text_field :level %> <br>

        <%= f.label :student_id %> <br>
        <%= f.text_field :student_id %> <br>

        <br>
        <%= f.submit "Save", class:"btn btn-success" %>
    <% end %>

</div>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> 
<br>
<br>
<div class="container">
    Title : <%= @exam.title %></br>
    Mapel : <%= @exam.mapel %></br>
    Duration : <%= @exam.duration %></br>
    Nilai : <%= @exam.nilai %></br>
    Keaktifan : <%= @exam.keaktifan %></br>
    Level : <%= @exam.level %></br>
    Student ID : <%= @exam.student_id %></br>
<br>
<%= link_to 'Back to Home', exams_path %>
</div>