config/routes.rb
Rails.application.routes.draw do
  
  # get 'payments/edit'
  # get 'payments/index'
  # get 'payments/show'
  # get 'payments/delete'
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments

  #get 'reports/edit'
  #get 'reports/index'
  #get 'reports/new'
  #get 'reports/show'
  #get 'exams/edit'
  # get 'exams/index'
  # get 'exams/new'
  # get 'exams/show'
  #get 'teachers/edit'
  #get 'teachers/index'
  #get 'teachers/new'
  #get 'teachers/show'
  #get 'students/edit'
  #get 'students/index'
  #get 'students/new'
  #get 'students/show'
  #get 'books/edit'
 # get 'books/index'
  #get 'books/new'
  #get 'books/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new #untuk menampilkan form data baru
    @report = Report.new
    # @report = Report.new(title: ' ')
    # @report = Report.new(page: nil)
    
  end

  def create #untuk memproses data baru yang dimasukan di form new
    #render plain: params.inspect -> cara mengecek apa isi params
    #title = params[:report][:title] ->caea mengecek balikan params
    report = Report.new(resource_params)
    report.save
    flash[:notice] = 'Report has been created'
    #puts report.errors.messages
    redirect_to reports_path
  end

  def edit # menampilkan data yang sudah disimpian di edit
    @report = Report.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
    @report = Report.find(params[:id])
    @report.update(resource_params)
    flash[:notice] = 'Report has been updated'
    redirect_to report_path(@report)
  end

  def destroy #untuk menghapus data
    @report = Report.find(params[:id])
    @report.destroy
    flash[:notice] = 'Report has been deleted'
    redirect_to reports_path
  end

  def index #menampilkan seluruh data yang ada di database
    @reports = Report.all
  end

  def show #menampilkan sebuah data secara detail
    id = params[:id]
    @report = Report.find(id) #-> id ini ngambil variabel diatas
    #render plain: id
    #render plain: @report.title
  end

  private

  def resource_params
    params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<br>

<div class="container">
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
<%= link_to 'Cancel', reports_path %>

<%= form_for(@report) do |f| %>
    <%= f.label :title %> <br>
    <%= f.text_field :title %> <br>

    <%= f.label :hasil %> <br>
    <%= f.text_field :hasil %> <br>

    <%= f.label :mapel %> <br>
    <%= f.text_field :mapel %> <br>

    <%= f.label :teacher_id %> <br>
    <%= f.text_field :teacher_id %> <br>

    <%= f.label :student_id %> <br>
    <%= f.text_field :student_id %> <br>

    <%= f.label :date %> <br>
    <%= f.text_field :date %> <br><br>

    <%= f.submit "Update Report", class:"btn btn-success" %>
<% end %>
</div>

app/views/reports/index.html.erb
<% if flash[:notice].present? %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

<table class="table table-bordered" >
    <thead class="thead-dark">
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Hasil</th>
            <th scope="col">Mapel</th>
            <th scope="col">Teacher ID</th>
            <th scope="col">Student ID</th>
            <th scope="col">Date</th>
            <th scope="col">Aksi</th>
        </tr>
    </thead>
        <% @reports.each do |report| %>
    <tbody>
        <tr>
            <td><%= report.title %></td>
            <td><%= report.hasil %></td>
            <td><%= report.mapel %></td>
            <td><%= report.teacher_id %></td>
            <td><%= report.student_id %></td>
            <td><%= report.date %></td>
            <td><%= link_to 'Detail', report_path(report), class:"btn btn-info" %>  <%= link_to 'Edit', edit_report_path(report), class:"btn btn-warning" %>  <%= link_to 'Delete', report_path(report), class:"btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %> </td>
        </tr>
    </tbody>
    <% end %>
</table> 

<div class="-25 p-3">
    <%= link_to 'New Report', new_report_path, class:"btn btn-success"%>
</div>

app/views/reports/new.html.erb
<br>
<div class="container">

<%= form_for(@report) do |f| %>
    <%= f.label :title %> <br>
    <%= f.text_field :title %> <br>

    <%= f.label :hasil %> <br>
    <%= f.text_field :hasil %> <br>

    <%= f.label :mapel %> <br>
    <%= f.text_field :mapel %> <br>

    <%= f.label :teacher_id %> <br>
    <%= f.text_field :teacher_id %> <br>

    <%= f.label :student_id %> <br>
    <%= f.text_field :student_id %> <br>

    <%= f.label :date %> <br>
    <%= f.text_field :date %> <br>

    <br>
    <%= f.submit "Save", class:"btn btn-success" %>
<% end %>
</div>

app/views/reports/show.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
<% end %> 
<br>
<br>
<div class="container">
    Title : <%= @report.title %></br>
    Hasil : <%= @report.hasil %></br>
    Mapel : <%= @report.mapel %></br>
    TeacherID : <%= @report.teacher_id %></br>
    StudentID : <%= @report.student_id %></br>
    Date : <%= @report.date %></br>
<br>
<%= link_to 'Back to Home', reports_path %>
</div>